/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GoingRouteImport } from './routes/going'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as MapRouteImport } from './routes/map'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as YouRouteImport } from './routes/you'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as DmIdRouteImport } from './routes/dm.$id'
import { Route as DoorIdRouteImport } from './routes/door.$id'
import { Route as DropIdRouteImport } from './routes/drop.$id'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostIdRouteImport } from './routes/host.$id'
import { Route as HostPayoutsRouteImport } from './routes/host.payouts'
import { Route as HostStartRouteImport } from './routes/host.start'
import { Route as HostTemplatesRouteImport } from './routes/host.templates'
import { Route as KeepIdRouteImport } from './routes/keep.$id'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NotificationsOptinRouteImport } from './routes/notifications.optin'
import { Route as NotificationsPreviewRouteImport } from './routes/notifications.preview'
import { Route as NotificationsRetentionRouteImport } from './routes/notifications.retention'
import { Route as OrganiserIdRouteImport } from './routes/organiser.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as PlanIdRouteImport } from './routes/plan.$id'
import { Route as PlanNewRouteImport } from './routes/plan.new'
import { Route as QrIdRouteImport } from './routes/qr.$id'
import { Route as RecapIdRouteImport } from './routes/recap.$id'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as VenueIndexRouteImport } from './routes/venue.index'
import { Route as VenueBillingRouteImport } from './routes/venue.billing'
import { Route as VenueClaimRouteImport } from './routes/venue.claim'
import { Route as VenueFillRouteImport } from './routes/venue.fill'
import { Route as WIdRouteImport } from './routes/w.$id'
import { Route as XIdRouteImport } from './routes/x.$id'
import { Route as HostBoostIdRouteImport } from './routes/host.boost.$id'
import { Route as HostEditIdRouteImport } from './routes/host.edit.$id'
import { Route as HostMessageIdRouteImport } from './routes/host.message.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoingRoute = GoingRouteImport.update({
  id: '/going',
  path: '/going',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DmIdRoute = DmIdRouteImport.update({
  id: '/dm/$id',
  path: '/dm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorIdRoute = DoorIdRouteImport.update({
  id: '/door/$id',
  path: '/door/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DropIdRoute = DropIdRouteImport.update({
  id: '/drop/$id',
  path: '/drop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIdRoute = HostIdRouteImport.update({
  id: '/host/$id',
  path: '/host/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostPayoutsRoute = HostPayoutsRouteImport.update({
  id: '/host/payouts',
  path: '/host/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const HostStartRoute = HostStartRouteImport.update({
  id: '/host/start',
  path: '/host/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HostTemplatesRoute = HostTemplatesRouteImport.update({
  id: '/host/templates',
  path: '/host/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepIdRoute = KeepIdRouteImport.update({
  id: '/keep/$id',
  path: '/keep/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsOptinRoute = NotificationsOptinRouteImport.update({
  id: '/notifications/optin',
  path: '/notifications/optin',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsPreviewRoute = NotificationsPreviewRouteImport.update({
  id: '/notifications/preview',
  path: '/notifications/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRetentionRoute = NotificationsRetentionRouteImport.update({
  id: '/notifications/retention',
  path: '/notifications/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserIdRoute = OrganiserIdRouteImport.update({
  id: '/organiser/$id',
  path: '/organiser/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNewRoute = PlanNewRouteImport.update({
  id: '/plan/new',
  path: '/plan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIdRoute = QrIdRouteImport.update({
  id: '/qr/$id',
  path: '/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapIdRoute = RecapIdRouteImport.update({
  id: '/recap/$id',
  path: '/recap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIndexRoute = VenueIndexRouteImport.update({
  id: '/venue/',
  path: '/venue/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueBillingRoute = VenueBillingRouteImport.update({
  id: '/venue/billing',
  path: '/venue/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueClaimRoute = VenueClaimRouteImport.update({
  id: '/venue/claim',
  path: '/venue/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueFillRoute = VenueFillRouteImport.update({
  id: '/venue/fill',
  path: '/venue/fill',
  getParentRoute: () => rootRouteImport,
} as any)
const WIdRoute = WIdRouteImport.update({
  id: '/w/$id',
  path: '/w/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const XIdRoute = XIdRouteImport.update({
  id: '/x/$id',
  path: '/x/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostBoostIdRoute = HostBoostIdRouteImport.update({
  id: '/host/boost/$id',
  path: '/host/boost/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEditIdRoute = HostEditIdRouteImport.update({
  id: '/host/edit/$id',
  path: '/host/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostMessageIdRoute = HostMessageIdRouteImport.update({
  id: '/host/message/$id',
  path: '/host/message/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/going': typeof GoingRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/onboard': typeof OnboardRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/chat/$id': typeof ChatIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dm/$id': typeof DmIdRoute
  '/door/$id': typeof DoorIdRoute
  '/drop/$id': typeof DropIdRoute
  '/e/$id': typeof EIdRoute
  '/event/$id': typeof EventIdRoute
  '/host/$id': typeof HostIdRoute
  '/host/payouts': typeof HostPayoutsRoute
  '/host/start': typeof HostStartRoute
  '/host/templates': typeof HostTemplatesRoute
  '/keep/$id': typeof KeepIdRoute
  '/notifications/optin': typeof NotificationsOptinRoute
  '/notifications/preview': typeof NotificationsPreviewRoute
  '/notifications/retention': typeof NotificationsRetentionRoute
  '/organiser/$id': typeof OrganiserIdRoute
  '/person/$id': typeof PersonIdRoute
  '/plan/$id': typeof PlanIdRoute
  '/plan/new': typeof PlanNewRoute
  '/qr/$id': typeof QrIdRoute
  '/recap/$id': typeof RecapIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/share/$id': typeof ShareIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/venue/billing': typeof VenueBillingRoute
  '/venue/claim': typeof VenueClaimRoute
  '/venue/fill': typeof VenueFillRoute
  '/w/$id': typeof WIdRoute
  '/x/$id': typeof XIdRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/host/boost/$id': typeof HostBoostIdRoute
  '/host/edit/$id': typeof HostEditIdRoute
  '/host/message/$id': typeof HostMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/going': typeof GoingRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/onboard': typeof OnboardRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/chat/$id': typeof ChatIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dm/$id': typeof DmIdRoute
  '/door/$id': typeof DoorIdRoute
  '/drop/$id': typeof DropIdRoute
  '/e/$id': typeof EIdRoute
  '/event/$id': typeof EventIdRoute
  '/host/$id': typeof HostIdRoute
  '/host/payouts': typeof HostPayoutsRoute
  '/host/start': typeof HostStartRoute
  '/host/templates': typeof HostTemplatesRoute
  '/keep/$id': typeof KeepIdRoute
  '/notifications/optin': typeof NotificationsOptinRoute
  '/notifications/preview': typeof NotificationsPreviewRoute
  '/notifications/retention': typeof NotificationsRetentionRoute
  '/organiser/$id': typeof OrganiserIdRoute
  '/person/$id': typeof PersonIdRoute
  '/plan/$id': typeof PlanIdRoute
  '/plan/new': typeof PlanNewRoute
  '/qr/$id': typeof QrIdRoute
  '/recap/$id': typeof RecapIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/share/$id': typeof ShareIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/venue/billing': typeof VenueBillingRoute
  '/venue/claim': typeof VenueClaimRoute
  '/venue/fill': typeof VenueFillRoute
  '/w/$id': typeof WIdRoute
  '/x/$id': typeof XIdRoute
  '/admin': typeof AdminIndexRoute
  '/host': typeof HostIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/venue': typeof VenueIndexRoute
  '/host/boost/$id': typeof HostBoostIdRoute
  '/host/edit/$id': typeof HostEditIdRoute
  '/host/message/$id': typeof HostMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/going': typeof GoingRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/onboard': typeof OnboardRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/chat/$id': typeof ChatIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dm/$id': typeof DmIdRoute
  '/door/$id': typeof DoorIdRoute
  '/drop/$id': typeof DropIdRoute
  '/e/$id': typeof EIdRoute
  '/event/$id': typeof EventIdRoute
  '/host/$id': typeof HostIdRoute
  '/host/payouts': typeof HostPayoutsRoute
  '/host/start': typeof HostStartRoute
  '/host/templates': typeof HostTemplatesRoute
  '/keep/$id': typeof KeepIdRoute
  '/notifications/optin': typeof NotificationsOptinRoute
  '/notifications/preview': typeof NotificationsPreviewRoute
  '/notifications/retention': typeof NotificationsRetentionRoute
  '/organiser/$id': typeof OrganiserIdRoute
  '/person/$id': typeof PersonIdRoute
  '/plan/$id': typeof PlanIdRoute
  '/plan/new': typeof PlanNewRoute
  '/qr/$id': typeof QrIdRoute
  '/recap/$id': typeof RecapIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/share/$id': typeof ShareIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/venue/billing': typeof VenueBillingRoute
  '/venue/claim': typeof VenueClaimRoute
  '/venue/fill': typeof VenueFillRoute
  '/w/$id': typeof WIdRoute
  '/x/$id': typeof XIdRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/host/boost/$id': typeof HostBoostIdRoute
  '/host/edit/$id': typeof HostEditIdRoute
  '/host/message/$id': typeof HostMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/auth'
    | '/connections'
    | '/create'
    | '/going'
    | '/inbox'
    | '/invite'
    | '/map'
    | '/membership'
    | '/memories'
    | '/messages'
    | '/onboard'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/saved'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/welcome'
    | '/you'
    | '/chat/$id'
    | '/checkout/$id'
    | '/dm/$id'
    | '/door/$id'
    | '/drop/$id'
    | '/e/$id'
    | '/event/$id'
    | '/host/$id'
    | '/host/payouts'
    | '/host/start'
    | '/host/templates'
    | '/keep/$id'
    | '/notifications/optin'
    | '/notifications/preview'
    | '/notifications/retention'
    | '/organiser/$id'
    | '/person/$id'
    | '/plan/$id'
    | '/plan/new'
    | '/qr/$id'
    | '/recap/$id'
    | '/review/$id'
    | '/series/$id'
    | '/share/$id'
    | '/ticket/$id'
    | '/venue/billing'
    | '/venue/claim'
    | '/venue/fill'
    | '/w/$id'
    | '/x/$id'
    | '/admin/'
    | '/host/'
    | '/notifications/'
    | '/venue/'
    | '/host/boost/$id'
    | '/host/edit/$id'
    | '/host/message/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/auth'
    | '/connections'
    | '/create'
    | '/going'
    | '/inbox'
    | '/invite'
    | '/map'
    | '/membership'
    | '/memories'
    | '/messages'
    | '/onboard'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/saved'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/welcome'
    | '/you'
    | '/chat/$id'
    | '/checkout/$id'
    | '/dm/$id'
    | '/door/$id'
    | '/drop/$id'
    | '/e/$id'
    | '/event/$id'
    | '/host/$id'
    | '/host/payouts'
    | '/host/start'
    | '/host/templates'
    | '/keep/$id'
    | '/notifications/optin'
    | '/notifications/preview'
    | '/notifications/retention'
    | '/organiser/$id'
    | '/person/$id'
    | '/plan/$id'
    | '/plan/new'
    | '/qr/$id'
    | '/recap/$id'
    | '/review/$id'
    | '/series/$id'
    | '/share/$id'
    | '/ticket/$id'
    | '/venue/billing'
    | '/venue/claim'
    | '/venue/fill'
    | '/w/$id'
    | '/x/$id'
    | '/admin'
    | '/host'
    | '/notifications'
    | '/venue'
    | '/host/boost/$id'
    | '/host/edit/$id'
    | '/host/message/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/auth'
    | '/connections'
    | '/create'
    | '/going'
    | '/inbox'
    | '/invite'
    | '/map'
    | '/membership'
    | '/memories'
    | '/messages'
    | '/onboard'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/saved'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/welcome'
    | '/you'
    | '/chat/$id'
    | '/checkout/$id'
    | '/dm/$id'
    | '/door/$id'
    | '/drop/$id'
    | '/e/$id'
    | '/event/$id'
    | '/host/$id'
    | '/host/payouts'
    | '/host/start'
    | '/host/templates'
    | '/keep/$id'
    | '/notifications/optin'
    | '/notifications/preview'
    | '/notifications/retention'
    | '/organiser/$id'
    | '/person/$id'
    | '/plan/$id'
    | '/plan/new'
    | '/qr/$id'
    | '/recap/$id'
    | '/review/$id'
    | '/series/$id'
    | '/share/$id'
    | '/ticket/$id'
    | '/venue/billing'
    | '/venue/claim'
    | '/venue/fill'
    | '/w/$id'
    | '/x/$id'
    | '/admin/'
    | '/host/'
    | '/notifications/'
    | '/venue/'
    | '/host/boost/$id'
    | '/host/edit/$id'
    | '/host/message/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CreateRoute: typeof CreateRoute
  GoingRoute: typeof GoingRoute
  InboxRoute: typeof InboxRoute
  InviteRoute: typeof InviteRoute
  MapRoute: typeof MapRoute
  MembershipRoute: typeof MembershipRoute
  MemoriesRoute: typeof MemoriesRoute
  MessagesRoute: typeof MessagesRoute
  OnboardRoute: typeof OnboardRoute
  PeopleRoute: typeof PeopleRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  YouRoute: typeof YouRoute
  ChatIdRoute: typeof ChatIdRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  DmIdRoute: typeof DmIdRoute
  DoorIdRoute: typeof DoorIdRoute
  DropIdRoute: typeof DropIdRoute
  EIdRoute: typeof EIdRoute
  EventIdRoute: typeof EventIdRoute
  HostIdRoute: typeof HostIdRoute
  HostPayoutsRoute: typeof HostPayoutsRoute
  HostStartRoute: typeof HostStartRoute
  HostTemplatesRoute: typeof HostTemplatesRoute
  KeepIdRoute: typeof KeepIdRoute
  NotificationsOptinRoute: typeof NotificationsOptinRoute
  NotificationsPreviewRoute: typeof NotificationsPreviewRoute
  NotificationsRetentionRoute: typeof NotificationsRetentionRoute
  OrganiserIdRoute: typeof OrganiserIdRoute
  PersonIdRoute: typeof PersonIdRoute
  PlanIdRoute: typeof PlanIdRoute
  PlanNewRoute: typeof PlanNewRoute
  QrIdRoute: typeof QrIdRoute
  RecapIdRoute: typeof RecapIdRoute
  ReviewIdRoute: typeof ReviewIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  ShareIdRoute: typeof ShareIdRoute
  TicketIdRoute: typeof TicketIdRoute
  VenueBillingRoute: typeof VenueBillingRoute
  VenueClaimRoute: typeof VenueClaimRoute
  VenueFillRoute: typeof VenueFillRoute
  WIdRoute: typeof WIdRoute
  XIdRoute: typeof XIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HostIndexRoute: typeof HostIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  VenueIndexRoute: typeof VenueIndexRoute
  HostBoostIdRoute: typeof HostBoostIdRoute
  HostEditIdRoute: typeof HostEditIdRoute
  HostMessageIdRoute: typeof HostMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/going': {
      id: '/going'
      path: '/going'
      fullPath: '/going'
      preLoaderRoute: typeof GoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$id': {
      id: '/dm/$id'
      path: '/dm/$id'
      fullPath: '/dm/$id'
      preLoaderRoute: typeof DmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/door/$id': {
      id: '/door/$id'
      path: '/door/$id'
      fullPath: '/door/$id'
      preLoaderRoute: typeof DoorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop/$id': {
      id: '/drop/$id'
      path: '/drop/$id'
      fullPath: '/drop/$id'
      preLoaderRoute: typeof DropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$id': {
      id: '/host/$id'
      path: '/host/$id'
      fullPath: '/host/$id'
      preLoaderRoute: typeof HostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/payouts': {
      id: '/host/payouts'
      path: '/host/payouts'
      fullPath: '/host/payouts'
      preLoaderRoute: typeof HostPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/start': {
      id: '/host/start'
      path: '/host/start'
      fullPath: '/host/start'
      preLoaderRoute: typeof HostStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/templates': {
      id: '/host/templates'
      path: '/host/templates'
      fullPath: '/host/templates'
      preLoaderRoute: typeof HostTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep/$id': {
      id: '/keep/$id'
      path: '/keep/$id'
      fullPath: '/keep/$id'
      preLoaderRoute: typeof KeepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/optin': {
      id: '/notifications/optin'
      path: '/notifications/optin'
      fullPath: '/notifications/optin'
      preLoaderRoute: typeof NotificationsOptinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/preview': {
      id: '/notifications/preview'
      path: '/notifications/preview'
      fullPath: '/notifications/preview'
      preLoaderRoute: typeof NotificationsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/retention': {
      id: '/notifications/retention'
      path: '/notifications/retention'
      fullPath: '/notifications/retention'
      preLoaderRoute: typeof NotificationsRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/$id': {
      id: '/organiser/$id'
      path: '/organiser/$id'
      fullPath: '/organiser/$id'
      preLoaderRoute: typeof OrganiserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/new': {
      id: '/plan/new'
      path: '/plan/new'
      fullPath: '/plan/new'
      preLoaderRoute: typeof PlanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$id': {
      id: '/qr/$id'
      path: '/qr/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof QrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$id': {
      id: '/recap/$id'
      path: '/recap/$id'
      fullPath: '/recap/$id'
      preLoaderRoute: typeof RecapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/': {
      id: '/venue/'
      path: '/venue'
      fullPath: '/venue/'
      preLoaderRoute: typeof VenueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/billing': {
      id: '/venue/billing'
      path: '/venue/billing'
      fullPath: '/venue/billing'
      preLoaderRoute: typeof VenueBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/claim': {
      id: '/venue/claim'
      path: '/venue/claim'
      fullPath: '/venue/claim'
      preLoaderRoute: typeof VenueClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/fill': {
      id: '/venue/fill'
      path: '/venue/fill'
      fullPath: '/venue/fill'
      preLoaderRoute: typeof VenueFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$id': {
      id: '/w/$id'
      path: '/w/$id'
      fullPath: '/w/$id'
      preLoaderRoute: typeof WIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/$id': {
      id: '/x/$id'
      path: '/x/$id'
      fullPath: '/x/$id'
      preLoaderRoute: typeof XIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/boost/$id': {
      id: '/host/boost/$id'
      path: '/host/boost/$id'
      fullPath: '/host/boost/$id'
      preLoaderRoute: typeof HostBoostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/edit/$id': {
      id: '/host/edit/$id'
      path: '/host/edit/$id'
      fullPath: '/host/edit/$id'
      preLoaderRoute: typeof HostEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/message/$id': {
      id: '/host/message/$id'
      path: '/host/message/$id'
      fullPath: '/host/message/$id'
      preLoaderRoute: typeof HostMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  ConnectionsRoute: ConnectionsRoute,
  CreateRoute: CreateRoute,
  GoingRoute: GoingRoute,
  InboxRoute: InboxRoute,
  InviteRoute: InviteRoute,
  MapRoute: MapRoute,
  MembershipRoute: MembershipRoute,
  MemoriesRoute: MemoriesRoute,
  MessagesRoute: MessagesRoute,
  OnboardRoute: OnboardRoute,
  PeopleRoute: PeopleRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  YouRoute: YouRoute,
  ChatIdRoute: ChatIdRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  DmIdRoute: DmIdRoute,
  DoorIdRoute: DoorIdRoute,
  DropIdRoute: DropIdRoute,
  EIdRoute: EIdRoute,
  EventIdRoute: EventIdRoute,
  HostIdRoute: HostIdRoute,
  HostPayoutsRoute: HostPayoutsRoute,
  HostStartRoute: HostStartRoute,
  HostTemplatesRoute: HostTemplatesRoute,
  KeepIdRoute: KeepIdRoute,
  NotificationsOptinRoute: NotificationsOptinRoute,
  NotificationsPreviewRoute: NotificationsPreviewRoute,
  NotificationsRetentionRoute: NotificationsRetentionRoute,
  OrganiserIdRoute: OrganiserIdRoute,
  PersonIdRoute: PersonIdRoute,
  PlanIdRoute: PlanIdRoute,
  PlanNewRoute: PlanNewRoute,
  QrIdRoute: QrIdRoute,
  RecapIdRoute: RecapIdRoute,
  ReviewIdRoute: ReviewIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  ShareIdRoute: ShareIdRoute,
  TicketIdRoute: TicketIdRoute,
  VenueBillingRoute: VenueBillingRoute,
  VenueClaimRoute: VenueClaimRoute,
  VenueFillRoute: VenueFillRoute,
  WIdRoute: WIdRoute,
  XIdRoute: XIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HostIndexRoute: HostIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  VenueIndexRoute: VenueIndexRoute,
  HostBoostIdRoute: HostBoostIdRoute,
  HostEditIdRoute: HostEditIdRoute,
  HostMessageIdRoute: HostMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
